# -------- Set up Backend --------
FROM node:20 AS backend

WORKDIR /usr/src/app

# Copy package files first for better caching
COPY backend/package*.json ./

# Install dependencies
RUN npm install --force

# Copy backend source code
COPY backend/ ./

# Expose port 5000 for the backend server
EXPOSE 5000

# Start the backend server
CMD ["node", "server.js"]
